### ISSUE TITLE
Chore: New Release

### ISSUE THREAD

**Issue by Green-Sky** [icculus/physfs#16]
The last Release was some years ago again. ("March 18th, 2019: 3.0.2 released!")
Would probably make sense to make a Release soon.

**Comment by icculus** [comment]
Agreed. There's a few more small fixes pending, and we can do a 3.0.3 release after that.

**Comment by icculus** [comment]
I think I'm going to take the main branch and call it a 3.2 release (there are a few new functions since 3.0.2, but I'm not ready for the serious redesign I want to do for a hypothetical PhysicsFS 4.0).

@sezero, any objections to me doing that? I'm going to resolve a few of the open bugs first, but otherwise are you okay with shipping the main branch as 3.2?

**Comment by sezero** [comment]
> @sezero, any objections to me doing that? I'm going to resolve a few of the open bugs first, but otherwise are you okay with shipping the main branch as 3.2?

Sure

**Comment by icculus** [comment]
Probably going to do the release sometime tomorrow (September 30th).

**Comment by icculus** [comment]
We are live!

The main branch has split off to the `stable-3.2` branch, which will only get fixes; new development (including ripping things up for PhysicsFS 4.0, eventually) will remain on `main`. The first release from `stable-3.2`, 3.2.0, is here:

https://github.com/icculus/physfs/releases/tag/release-3.2.0

I've also done a release-3.0.3, which is the final thing in the `stable-3.0` branch. This is just bugfixes and no big changes over the previous 3.0.2 branch, and is just for completeness and extremely risk-adverse upgraders...all releases are still API/ABI compatible with PhysicsFS 1.0, so generally there's no reason not to go straight to 3.2.0 here.

I do not intend to make any more commits to `stable-3.0` or do another 3.0.x release. 3.2.x will get bugfixes, main will get new features.

**Comment by Green-Sky** [comment]
Nice, well done!
