### ISSUE TITLE
PhysFS considers some .zip files modified by Windows Explorer corrupted

### ISSUE THREAD

**Issue by Dav999-v** [icculus/physfs#24]
This has been affecting [VVVVVV](https://github.com/TerryCavanagh/VVVVVV), which uses PhysFS, and which uses a `data.zip` file with the game's assets (found [here](https://thelettervsixtim.es/makeandplay/), via [Desktop data file]). Whenever people would add/remove any file in the zip with Windows Explorer, the entire zip would become (seemingly) completely unreadable to the game.

Digging into this deeper, this is caused by a validity check in PhysFS. These are some reproduction steps:

1. Start a zip file with 2 files with software that sets the `Extract OS` in file's headers to something other than `00` 'MS-DOS' (I used Engrampa which came with my Linux distro, apparently `zip` from the terminal does not qualify.) Here's my version: [test-2unix.zip](https://github.com/icculus/physfs/files/8735094/test-2unix.zip)

2. Observe the headers with `zipdetails`:

```
0000 LOCAL HEADER #1       04034B50
0004 Extract Zip Spec      0A '1.0'
0005 Extract OS            03 'Unix'
[...]

0037 LOCAL HEADER #2       04034B50
003B Extract Zip Spec      0A '1.0'
003C Extract OS            03 'Unix'
[...]

006E CENTRAL HEADER #1     02014B50
0072 Created Zip Spec      3F '6.3'
0073 Created OS            03 'Unix'
0074 Extract Zip Spec      0A '1.0'
0075 Extract OS            03 'Unix'
[...]

00C5 CENTRAL HEADER #2     02014B50
00C9 Created Zip Spec      3F '6.3'
00CA Created OS            03 'Unix'
00CB Extract Zip Spec      0A '1.0'
00CC Extract OS            03 'Unix'
[...]
```

3. In Windows Explorer (tested with Windows 10 and 11), drag and drop a third file into the zip. My result: [test-2unix-1ms.zip](https://github.com/icculus/physfs/files/8735100/test-2unix-1ms.zip)

4. Observe the new headers with `zipdetails`:

```
0000 LOCAL HEADER #1       04034B50
0004 Extract Zip Spec      0A '1.0'
0005 Extract OS            03 'Unix'
[...]

0037 LOCAL HEADER #2       04034B50
003B Extract Zip Spec      0A '1.0'
003C Extract OS            03 'Unix'
[...]

006E LOCAL HEADER #3       04034B50
0072 Extract Zip Spec      14 '2.0'
0073 Extract OS            00 'MS-DOS'
[...]

00A5 CENTRAL HEADER #1     02014B50
00A9 Created Zip Spec      14 '2.0'
00AA Created OS            00 'MS-DOS'
00AB Extract Zip Spec      14 '2.0'
00AC Extract OS            00 'MS-DOS'
[...]

00FC CENTRAL HEADER #2     02014B50
0100 Created Zip Spec      14 '2.0'
0101 Created OS            00 'MS-DOS'
0102 Extract Zip Spec      14 '2.0'
0103 Extract OS            00 'MS-DOS'
[...]

0153 CENTRAL HEADER #3     02014B50
0157 Created Zip Spec      14 '2.0'
0158 Created OS            00 'MS-DOS'
0159 Extract Zip Spec      14 '2.0'
015A Extract OS            00 'MS-DOS'
[...]
```

5. PhysFS now considers the first two files corrupted and refuses to process them.

So what Windows Explorer apparently does when it modifies the zip file is update the version numbers/OS for all existing files in the central headers, but it leaves them as-is in the local headers.

The check in PhysFS which fails is in `zip_parse_local` in `physfs_archiver_zip.c`, specifically `ui16 != entry->version_needed`. `ui16` being Extract Zip Spec/Extract OS in a local header, and `entry->version_needed` being Extract Zip Spec/Extract OS in the corresponding central header.

Adding this `printf` demonstrates it:

```diff
diff --git a/src/physfs_archiver_zip.c b/src/physfs_archiver_zip.c
index 9972628..99d4dbc 100644
--- a/src/physfs_archiver_zip.c
+++ b/src/physfs_archiver_zip.c
@@ -833,6 +833,9 @@ static int zip_parse_local(PHYSFS_Io *io, ZIPentry *entry)
     BAIL_IF_ERRPASS(!readui32(io, &ui32), 0);
     BAIL_IF(ui32 != ZIP_LOCAL_FILE_SIG, PHYSFS_ERR_CORRUPT, 0);
     BAIL_IF_ERRPASS(!readui16(io, &ui16), 0);
+    printf("ui16: 0x%04x, entry->version_needed: 0x%04x\n",
+        ui16, entry->version_needed
+    );
     BAIL_IF(ui16 != entry->version_needed, PHYSFS_ERR_CORRUPT, 0);
     BAIL_IF_ERRPASS(!readui16(io, &ui16), 0);  /* general bits. */
     BAIL_IF_ERRPASS(!readui16(io, &ui16), 0);
```

The output from my "minimal" test program ([main.c](https://gist.github.com/Dav999-v/ac0df88b883ac4318bc1c03d233f322c)) is as follows for the Unix-only zip:

```
$ ./main test-2unix.zip 
ui16: 0x030a, entry->version_needed: 0x030a
ui16: 0x030a, entry->version_needed: 0x030a
File a.txt: 20/20 bytes
File b.txt: 20/20 bytes
```

And this for the Explorer-modified zip:

```
$ ./main test-2unix-1ms.zip 
ui16: 0x0014, entry->version_needed: 0x0014
ui16: 0x030a, entry->version_needed: 0x0014
Cannot enumerate files! corrupted
```

So, I don't know whether Explorer is in the wrong here by updating one type of header and not the other, or whether PhysFS makes an incorrect assumption that this is invalid, but other software seems to have no problems with these zips.

**Comment by icculus** [comment]
Explorer is wrong here, but this is easy to workaround; we'll stop treating it as corruption and just favor the info in the local header for that field.
