### ISSUE TITLE
Fix physfsrwops_write

### ISSUE THREAD

**Issue by SDLBugzilla** [icculus/physfs#28]
# This bug report was migrated from our old Bugzilla tracker.

These attachments are available in the static archive:

* [Patch against tip (file_6398.txt, text/plain, 2015-07-30 20:34:32 -0400, 732 bytes)](https://bugzilla.icculus.org/attachment.cgi?id=3544)

**Reported in version:** all
**Reported for operating system, platform:** All, All

# Comments on the original bug report:

On 2015-07-30 20:34:32 -0400, rettichschnidi wrote:

> Created attachment 3544
> Patch against tip
> 
> physfsrwops_write does not return what is specified in the documentation of SDL's read function in SDL_RWops.

On 2015-07-30 20:38:05 -0400, rettichschnidi wrote:

> /read function/write function/

**Comment by icculus** [comment]
This got fixed at some point.
