### ISSUE TITLE
64 bit division on a 32 bit system fails to link

### ISSUE THREAD

**Issue by SDLBugzilla** [icculus/physfs#29]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** all
**Reported for operating system, platform:** All, PC

# Comments on the original bug report:

On 2013-06-04 01:27:59 -0400, buckyballreaction@gmail.com wrote:

> When compiling physicsfs with gcc on a 32bit Linux or OSX system, the library fails to link with the following error:
> 
> undefined reference to `__divdi3'
> 
> This is because of the 64 bit division in PHYSFS_read() and PHYSFS_write() with the line:
> 
> return ( (retval <= 0) ? retval : (retval / ((PHYSFS_sint64) size)) );
> 
> 
> I found some similar discussion on the topic here:
> 
> http://stackoverflow.com/questions/35463/how-to-divide-two-64-bit-numbers-in-linux-kernel
> 
> Thanks for any help

On 2013-06-04 10:08:36 -0400, buckyballreaction@gmail.com wrote:

> I forgot to add that this occurs with static linking

On 2013-12-05 15:50:23 -0500, Matthias MailÃ¤nder wrote:

> I think http://software.opensuse.org/package/libphysfs1 are also effected by this. It does not work at all for me on i586 (tried Blobby Volley 2 and Hedgewars).

**Comment by icculus** [comment]
This needed the C runtime linked in, I think...?
