### ISSUE TITLE
Build fails due to -Werror

### ISSUE THREAD

**Issue by SDLBugzilla** [icculus/physfs#30]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** all
**Reported for operating system, platform:** Windows NT, PC

# Comments on the original bug report:

On 2015-02-07 07:44:17 -0500, Aleksi Juvani wrote:

> 2.0.3 build fails on 64-bit Windows 8 with MinGW and GCC 4.8.0 with the following errors:
> 
> ```
>  physfs-2.0.3/archivers/lzma.c: In function 'SzFileReadImp':
>  physfs-2.0.3/archivers/lzma.c:133:46: error: cast from pointer to integer of different size [-Werror=pointer-to-int-cast]
>      FileInputStream *s = (FileInputStream *)((unsigned long)object - offsetof(FileInputStream, inStream)); /* HACK! */
>                                               ^
> physfs-2.0.3/archivers/lzma.c: In function 'SzFileSeekImp':
> physfs-2.0.3/archivers/lzma.c:148:46: error: cast from pointer to integer of different size [-Werror=pointer-to-int-cast]
>      FileInputStream *s = (FileInputStream *)((unsigned long)object - offsetof(FileInputStream, inStream)); /* HACK! */
>                                               ^
> cc1.exe: all warnings being treated as errors
> ```
>
> The development branch from the repository fails to build with the following errors:
>
> ```
> physfs/src/platform_windows.c: In function '__PHYSFS_platformEnumerateFiles':
> physfs/src/platform_windows.c:533:21: error: unused variable 'tag' [Werror=unused-variable]
>          const DWORD tag = entw.dwReserved0;
>                  ^
> physfs/src/platform_windows.c:532:21: error: unused variable 'attr' [Werror=unused-variable]
>          const DWORD attr = entw.dwFileAttributes;
>                  ^
> physfs/src/platform_windows.c: At top level:
> physfs/src/platform_windows.c:483:12: error: 'isSymlinkAttrs' defined but not used [-Werror=unused-function]
>  static int isSymlinkAttrs(const DWORD attr, const DWORD tag)
>         ^
> cc1.exe: all warnings being treated as errors
> ```
>
> Both build fine if I manually remove the -Werror flag from CMakeLists.txt. I'd recommend removing -Werror by default. It makes sense for development, but not as a default for every build.

On 2015-05-03 01:30:40 -0400, Bradley Bell wrote:

> cast to unsigned long seems pretty unnecessary there.
>
> ```diff
> diff -r aaa1204a4426 archivers/lzma.c
> --- a/archivers/lzma.c  Thu Aug 14 21:27:00 2014 -0400
> +++ b/archivers/lzma.c  Sat May 02 22:20:44 2015 -0700
> @@ -130,7 +130,7 @@
>  SZ_RESULT SzFileReadImp(void *object, void *buffer, size_t size,
>                          size_t *processedSize)
>  {
> -    FileInputStream *s = (FileInputStream *)((unsigned long)object - offsetof(FileInputStream, inStream)); /* HACK! */
> +    FileInputStream *s = (FileInputStream *)(object - offsetof(FileInputStream, inStream)); /* HACK! */
>      size_t processedSizeLoc = __PHYSFS_platformRead(s->file, buffer, 1, size);
>      if (processedSize != 0)
>          *processedSize = processedSizeLoc;
> @@ -145,7 +145,7 @@
>   */
>  SZ_RESULT SzFileSeekImp(void *object, CFileSize pos)
>  {
> -    FileInputStream *s = (FileInputStream *)((unsigned long)object - offsetof(FileInputStream, inStream)); /* HACK! */
> +    FileInputStream *s = (FileInputStream *)(object - offsetof(FileInputStream, inStream)); /* HACK! */
>      if (__PHYSFS_platformSeek(s->file, (PHYSFS_uint64) pos))
>          return SZ_OK;
>      return SZE_FAIL;
>```

**Comment by icculus** [comment]
I think these got resolved at some point.
