### ISSUE TITLE
Update LZMA archiver to latest LZMA SDK

### ISSUE THREAD

**Issue by SDLBugzilla** [icculus/physfs#34]
# This bug report was migrated from our old Bugzilla tracker.

These attachments are available in the static archive:

* [Patch to update the LZMA SDK and LZMA archiver (lzma938.diff, text/plain, 2015-01-10 09:39:41 -0500, 4514974 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=3508)

**Reported in version:** all
**Reported for operating system, platform:** All, PC

# Comments on the original bug report:

On 2015-01-10 09:39:41 -0500, Jan Hellwig wrote:

> Created attachment 3508
> Patch to update the LZMA SDK and LZMA archiver
> 
> Currently PhysicsFS uses an old version of the LZMA SDK. Since then the SDK has been updates with bugfixes, new features, etc. Also the license of the LZMA SDK was placed in the public domain (was LGPL before).
> As the API has changed quite a bit over the years the PhysicsFS LZMA archiver also needed to be update to work with the new LZMA SDK API.
> 
> I attached a patch file that does update the LZMA SDK as well as the LZMA archiver to the latest version.
> If you prefer to use the latest stable LZMA SDK (9.20, 4 years old), I do have a patch for that as well.

**Comment by icculus** [comment]
This got handled (and the SDK mushed down into a single header, too).
