### ISSUE TITLE
Android APK support

### ISSUE THREAD

**Issue by SDLBugzilla** [icculus/physfs#40]
# This bug report was migrated from our old Bugzilla tracker.

These attachments are available in the static archive:

* [Simple Android.mk file. Enables ZIP and APK support. (Android.mk, text/x-makefile, 2014-04-27 18:48:46 -0400, 585 bytes)](https://bugzilla.icculus.org/attachment.cgi?id=3439)
* [Patch with the implementation and the required changes for src/physfs.c and the CMake build script (physfs_apk_support.patch, text/plain, 2014-04-27 18:50:33 -0400, 4951 bytes)](https://bugzilla.icculus.org/attachment.cgi?id=3440)

**Reported in version:** all
**Reported for operating system, platform:** other, Other

# Comments on the original bug report:

On 2014-04-27 18:48:46 -0400, rettichschnidi wrote:

> Created attachment 3439
> Simple Android.mk file. Enables ZIP and APK support.
> 
> Based on the archiver_zip.c file I created a super simple hack which allows to use physfs to mount an Android APK file.
> 
> It basicly just prexfixes each filename with "/assets/" and then forwards the real work to the ZIP implementation in archiver_zip.c. 
> 
> There is also a simple Android.mk file which is configured to enable ZIP and APK support.

On 2014-04-27 18:50:33 -0400, rettichschnidi wrote:

> Created attachment 3440
> Patch with the implementation and the required changes for src/physfs.c and the CMake build script

**Comment by icculus** [comment]
The latest supports Android, and can open APK files with the ZIP archiver, plus PHYSFS_setRoot can get you past the "/assets" folder to make it look like any other .zip file full of game assets and not Android bits.
