### ISSUE TITLE
[Bug] Stack Pointer Leak Out-Of-Scope

### ISSUE THREAD

**Issue by TurtleP** [icculus/physfs#45]
While porting physfs to be usable on Wii U homebrew, it was discovered [this leaks a stack pointer out of scope](https://github.com/icculus/physfs/blob/main/src/physfs.c#L1044).

We found this because `PHYSFS_exists` was failing, so the parameters of `createDirHandle` were logged:
```
00;41;58;987: mountPoint pêÀT¸T/
00;41;58;987: dirName fs:/vol/external01/save/game
```
We have [patched this](https://github.com/TurtleP/physfs/blob/wiiu-physfs/src/physfs_internal.h#L152) to make the minimum for smallAlloc be zero to avoid this issue. Hopefully this is a trivial fix.

**Comment by icculus** [comment]
This doesn't appear to be incorrect in PhysicsFS (that alloca() pointer is only used within that function, being copied to a malloc'd buffer before returning).

alloca() pointers should live until the end of the function, not the end of the current `{}` scope. Is this is a bug in the Wii U's alloca() implementation? It's possible I'm misunderstanding the code here and thus not seeing the problem.

**Comment by TurtleP** [comment]
I checked in with some of the Wii U homebrew peeps, supposedly there is a bug in either devkitPPC or wut `alloca`, whichever it may be. They haven't entirely looked into it yet, but hopefully will do soon and be certain.
