### ISSUE TITLE
Cannot read/write to a file

### ISSUE THREAD

**Issue by bkeys** [icculus/physfs#70]
I have this code, which seems like everything I need to do to create a file in the root dir. But it fails because the file handler is NULL. Could you tell me what is wrong with this?
```
  PHYSFS_init(argv[0]);
  if (not PHYSFS_mount(PHYSFS_getPrefDir("bkeys_games", "Call of the Dead"),
                       NULL, 1)) {
    std::cout << "WHY????" << std::endl;
  }
  if (PHYSFS_setWriteDir("/")) {
    PHYSFS_ErrorCode error = PHYSFS_getLastErrorCode();
    std::cout << "files are open?" << std::endl;
  }
  PHYSFS_Stat stat = PHYSFS_Stat();
  PHYSFS_File *txtwtest = PHYSFS_openWrite("settings.xml");
  PHYSFS_ErrorCode error = PHYSFS_getLastErrorCode();
  int test = PHYSFS_writeBytes(txtwtest, "I am bkeys, kneel before me",
                               strlen("I am bkeys, kneel before me"));
  PHYSFS_close(txtwtest);
```

**Comment by icculus** [comment]
PHYSFS_setWriteDir() sets where files will be written _on the actual filesystem_, so you're trying to open "/settings.xml" for write.

Set the write directory to whatever `PHYSFS_getPrefDir("bkeys_games", "Call of the Dead")` returned, so it'll read and write files there by default.

**Comment by icculus** [comment]
(Unless you really wanted to open that in the root directory of the real filesystem and not the root directory of PhysicsFS's virtual file tree, in which case you probably just didn't have write permission from the OS.)

**Comment by bkeys** [comment]
Okay so I'm using OpenSceneGraph which simply asks for the path
```
osg::Node *node = osgDB::readNodeFile("somepath.dae");
```
and the function wants it relative to the binary. Is there a way to use PhysFS in this context?

**Comment by icculus** [comment]
> and the function wants it relative to the binary

```c
// getBaseDir tells you where the real binary lives, make that the root of the PhysicsFS tree.
PHYSFS_mount(PHYSFS_getBaseDir(), "/", 1);
PHYSFS_File *f = PHYSFS_openRead("somepath.dae");  // opens somepath.dae in the same directory as the binary.
```
