### ISSUE TITLE
RWops extras currently requires an update for SDL3

### ISSUE THREAD

**Issue by ShockSlayer** [icculus/physfs#77]
The migration document for SDL3 outlines some changes to the SDL_RWops read and write function signatures [here.](https://github.com/libsdl-org/SDL/blob/main/docs/README-migration.md#sdl_rwopsh)

Naturally, this means the custom RWops implementation example in (extras/physfsrwops.c) will need an update, since it passes functions that use the old signature.

With SDL3 still in a prerelease state, I would imagine it would be currently inadvisable to push any changes until that's solidified. That said, I figured I'd make a note of it here so that it's not forgotten...and because I don't know what I'm looking at yet, I'm not sure how to fix it myself.

**Comment by icculus** [comment]
Good call.

I _think_ we're done making changes to this part of SDL3, so it's probably safe to update PhysicsFS, but we'll let it marinate a little longer, just in case.

**Comment by EkajArmstro** [comment]
I attempted to do this, not sure if this is the right approach but it works well enough for my simple use case https://github.com/icculus/physfs/pull/81
