### ISSUE TITLE
PHYSFS_openRead() can find file only when run under gdb

### ISSUE THREAD

**Issue by mlauss2** [icculus/physfs#90]
In my app, with physfs latest github head dropped into the source tree, I do the following:

```
main.cpp:

PHYSFS_init(argv[0]);
PHYSFS_mount("somezip.zip", "/p1", 0);
PHYSFS_mount("/home/dev/path2", "/p1", 0);
PHYSFS_setWriteDir("/home/dev/path2");
int exists = PHYSFS_exists("/p1/existingfile")
PHYSFS_File* f = PHYSFS_openRead("/p1/existingfile");
```
"existingfile" resides in the "somezip.zip" file.

```exists``` returns 1 (i.e. found), BUT ```f``` is a nullptr, with error message ```failed: not found```

If I run the app under GDB though, the ```PHYSFS_openRead()``` correctly succeeds!

I can repeat these steps successfully in ```test_physfs``` (with or without GDB), so I guess I am doing something wrong, but I don't see what it could be.  Can anyone please shed some light on this?

Thanks!

**Comment by mlauss2** [comment]
Ok, this was me being stupid. Sorry for the noise.

**Comment by sezero** [comment]
OK, closing then :)
